### ISSUE TITLE
v0.5.8 Incorrect Threshold level

### ISSUE THREAD

**Issue by jglapa** [agorapulse/grails-sentry#17]
Hi is the 0.5.8 branch still supported? Moving to 0.6 would require quite a bit of work.

I've notice that the documentation is wrong about the event level being logged. 
It claims that everything above WARN will be logged but when I look here: https://github.com/agorapulse/grails-raven/blob/0.5.8/src/groovy/grails/plugins/raven/SentryAppender.groovy#L16 
I see threshold hardcoded to ERROR which should exclude the WARN events?

**Comment by benorama** [comment]
Sorry 0.5.8 is not maintained anymore. You might want to upgrade or publish internally your own version?
