### ISSUE TITLE
Add some default tags like "app", "grails_version", "env" and "version"

### ISSUE THREAD

**Issue by mhuebner** [agorapulse/grails-sentry#29]
These tags should be added by default as you won't be able to filter by "app" (projekt name) or "grails_version" in sentry.

**Comment by musketyr** [comment]
this sounds like a sensible default, I'll investigate the possibilities of doing so.

**Comment by mhuebner** [comment]
Defaults might be:

```
        def metadata = Metadata.getCurrent()
        tags['app'] = metadata.getApplicationName()
        tags['version'] = metadata.getApplicationVersion()
        tags['grails_version'] = metadata.getGrailsVersion()
        tags['env'] = metadata.getEnvironment()
```

**Comment by mhuebner** [comment]
There might also be a config setting to be able to control these tags.
