### ISSUE TITLE
raven-java is not longer maintained

### ISSUE THREAD

**Issue by jglapa** [agorapulse/grails-sentry#31]
Raven-java is not longer maintained as stated here: https://docs.sentry.io/clients/java/
Are there plans to upgrade this plugin? 

Also what is the current version?
The gh repo states `7.8.1` but bintray shows `8.0.3`. I cannot find any tag or branch to it.

**Comment by musketyr** [comment]
The latest is `8.0.3`. We are definitely going to support the new official libraries in next major release.
