### ISSUE TITLE
Process only ERROR level

### ISSUE THREAD

**Issue by jglapa** [agorapulse/grails-sentry#41]
How to configure the plugin to login only `ERROR` events?

Having this in my config I would expect only error events to be published
``` application.groovy
grails.plugin.sentry.levels = ['ERROR']
```

but looking at the source code it will fall back to the defaults which contains also `WARN`

https://github.com/agorapulse/grails-sentry/blob/d685058932a38866cadb5354ec55cd3e813e772a/src/main/groovy/grails/plugin/sentry/GrailsLogbackSentryAppender.groovy#L53-L57

**Comment by musketyr** [comment]
Well spotted. The condition should be changed.

**Comment by jglapa** [comment]
do you accept PRs?

**Comment by musketyr** [comment]
PRs are always welcomed!
