### ISSUE TITLE
Allow for tag adding

### ISSUE THREAD

**Issue by jglapa** [agorapulse/grails-sentry#42]
My use case is that I would like to add a tag to each event.
I cannot use the `grails.plugin.sentry.tags` config property because the value of that tag is known after the app has started.

In my case it's a grails config property but I imagine that you could also want to load it from a db or from somewhere else.
Using `MDC` would work but it's too much overhead ( I could create a filter to add it in each request but for not web context bound threads this would be difficult )

I found a way to do it as a big hack in `Bootstrap.groovy`
I'm basically adding this to the `SentryConfig` after the Appender has been initialized
```groovy
def sentryAppenderBeanName = 'sentryAppender'
if (grailsApplication.mainContext.containsBeanDefinition(sentryAppenderBeanName)) {
      def sentryAppender = grailsApplication.mainContext.getBean(sentryAppenderBeanName)
      sentryAppender.config.tags.put('mySpecialTag', grailsApplication.config.my.property)
}
```

**Comment by musketyr** [comment]
So how should the optimal solution look like?

**Comment by musketyr** [comment]
Instead of digging into the context, couldn't you just autowire `sentryAppender` into a service and change the settings inside the service as you want? e.g. using `InitializingBean` interface fallback.

**Comment by jglapa** [comment]
`Autowiring` I think is just a slightly better/different approach of what I do now.

IMHO best solution would be expose some explicit public methods for tags modification in either `SentryAppender` or `SentryConfig` that we could indeed Autowire but at least the contract would be uphold in future versions. 

With current situation I'm afraid that in future versions the config might become `private` thus forbidding what I do now.

**Comment by musketyr** [comment]
sound good. what about keeping the tags in mutable list which is populated from the config once the bean is initialised?

**Comment by jglapa** [comment]
I think this could also work but I don't know if I'll have full access to grails config(where my desired tag value resides) while the context is being configured.

**Comment by jglapa** [comment]
Wanted to contribute to this but eventually I found out that `SentryClient` has an `addTag(String,String) `method that does exactly what I need.

This can me closed from my perspective.

**Comment by musketyr** [comment]
Perfect!
