### ISSUE TITLE
`unknown` value for ipAddress is unable to be parsed by sentry.io

### ISSUE THREAD

**Issue by erichelgeson** [agorapulse/grails-sentry#45]
I recently forgot to turn on request logging (so the request obj was not available to parse) and the plugin tried to use the value `unknown` for the `ipAddress` of the `sentry.interfaces.User`. sentry.io was unable to parse this - 
<img width="591" alt="screen shot 2018-01-25 at 1 05 16 pm" src="https://user-images.githubusercontent.com/271734/35407148-92a4cc68-01d0-11e8-942c-9b90feee2730.png">

A work around may be as simple as having the default be `127.0.0.1` instead of unknown. Let me know (I can open a PR if that's an acceptable work around)

**Comment by musketyr** [comment]
Sounds good, you can definitely open a PR. Thanks
